// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo27JVhV_Mz8qy2owyWtIywyXniqhoBCc',
    appId: '1:496892134026:web:e682c2cc911e13aec66373',
    messagingSenderId: '496892134026',
    projectId: 'tic-tac-toe-pro-99928755',
    authDomain: 'tic-tac-toe-pro-99928755.firebaseapp.com',
    databaseURL: 'https://tic-tac-toe-pro-99928755-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-pro-99928755.appspot.com',
    measurementId: 'G-XBVHDW4Q6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIt3ijhYZ1_WEXgNYXAM8jmExk8rgV70A',
    appId: '1:496892134026:android:f8c1e649f3d6f22bc66373',
    messagingSenderId: '496892134026',
    projectId: 'tic-tac-toe-pro-99928755',
    databaseURL: 'https://tic-tac-toe-pro-99928755-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-pro-99928755.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3lGbWrTqt7eWsxlvHODng90sSpTf3wp8',
    appId: '1:496892134026:ios:ec8adfa5110dff01c66373',
    messagingSenderId: '496892134026',
    projectId: 'tic-tac-toe-pro-99928755',
    databaseURL: 'https://tic-tac-toe-pro-99928755-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-pro-99928755.appspot.com',
    iosBundleId: 'com.example.ticTacToePro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3lGbWrTqt7eWsxlvHODng90sSpTf3wp8',
    appId: '1:496892134026:ios:e240d07ae1603c00c66373',
    messagingSenderId: '496892134026',
    projectId: 'tic-tac-toe-pro-99928755',
    databaseURL: 'https://tic-tac-toe-pro-99928755-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-pro-99928755.appspot.com',
    iosBundleId: 'com.example.ticTacToePro.RunnerTests',
  );
}
